#ifndef COMMANDS_H
#define COMMANDS_H

DEF_COMMAND(CMD_PUSH, 1, );
DEF_COMMAND(CMD_POP, 2, );
DEF_COMMAND(CMD_IN, 3, );
DEF_COMMAND(CMD_ADD, 4, );
DEF_COMMAND(CMD_SUB, 5, );
DEF_COMMAND(CMD_MUL, 6, );
DEF_COMMAND(CMD_DIV, 7, );
DEF_COMMAND(CMD_SQRT, 8, );
DEF_COMMAND(CMD_SIN, 9, );
DEF_COMMAND(CMD_COS, 10, );
DEF_COMMAND(CMD_OUT, 11, );
DEF_COMMAND(CMD_HLT, 12, );


#endif