#ifndef COMMANDS_H
#define COMMANDS_H

DEF_COMMAND(PUSH, 1, );
DEF_COMMAND(POP, 2, );
DEF_COMMAND(IN, 3, );
DEF_COMMAND(ADD, 4, );
DEF_COMMAND(SUB, 5, );
DEF_COMMAND(MUL, 6, );
DEF_COMMAND(DIV, 7, );
DEF_COMMAND(SQRT, 8, );
DEF_COMMAND(SIN, 9, );
DEF_COMMAND(COS, 10, );
DEF_COMMAND(OUT, 11, );
DEF_COMMAND(HLT, 12, );


#endif